# Generated by Django 6.0.7 on 2026-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='external_id',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
