# Generated by Django 6.0.7 on 2026-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='bin_iin',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
