# Generated by Django 6.0.7 on 2026-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_orgmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmembership',
            name='is_admin',
            field=models.BooleanField(db_default=False, default=False, verbose_name='администратор организации'),
        ),
    ]
