# Generated by Django 6.0.7 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_orgmembership_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Собственник'), ('operator', 'Управляющая компания'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('expert', 'Эксперт'), ('designer', 'Проектировщик'), ('builder', 'Подрядчик СМР')], max_length=32),
        ),
    ]
