# Generated by Django 6.0.7 on 2026-09-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_dictbank_dictlineofbusiness_dictprofessionalholiday'),
        ('parties', '0006_alter_partyrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='line_of_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='dictionary.dictlineofbusiness', verbose_name='сфера деятельности'),
        ),
    ]
