# Generated by Django 6.0.7 on 2026-09-10 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_dictbank_dictlineofbusiness_dictprofessionalholiday'),
        ('parties', '0007_party_line_of_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='contacts',
        ),
        migrations.CreateModel(
            name='PartyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('born_on', models.DateField(blank=True, null=True, verbose_name='день рождения')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_records', to='parties.org', verbose_name='организация')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='parties.party', verbose_name='сторона')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'учётная карточка',
                'verbose_name_plural': 'учётные карточки',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='должность')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта')),
                ('born_on', models.DateField(blank=True, null=True, verbose_name='день рождения')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='parties.partyrecord', verbose_name='учётная карточка')),
            ],
            options={
                'verbose_name': 'контактное лицо',
                'verbose_name_plural': 'контактные лица',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=64, verbose_name='счёт (IBAN)')),
                ('kbe', models.CharField(blank=True, max_length=8, null=True, verbose_name='КБе')),
                ('is_primary', models.BooleanField(db_default=False, default=False, verbose_name='основной')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='dictionary.dictbank', verbose_name='банк')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='parties.partyrecord', verbose_name='учётная карточка')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комплект платёжных реквизитов',
                'verbose_name_plural': 'платёжные реквизиты',
                'ordering': ('-is_primary', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='partyrecord',
            constraint=models.UniqueConstraint(fields=('party', 'org'), name='party_record_uq'),
        ),
    ]
