# Generated by Django 6.0.7 on 2026-07-27 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_passport', '0006_alter_buildingpassport_table_and_more'),
        ('dictionary', '0005_dictassetrelationkind_dictconditiongrade_and_more'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='П-1, ЩС-3, ИТП-1', max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('criticality', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('design', 'Проект'), ('installed', 'Смонтирована'), ('commissioning', 'Пусконаладка'), ('operating', 'В работе'), ('standby', 'Резерв'), ('decommissioned', 'Выведена')], max_length=16, null=True)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='building_passport.space')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='dictionary.dictsystem')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='П-1 ⊂ приточная вентиляция ⊂ ОВиК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='engineering_systems.buildingsystem')),
                ('responsible_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_systems', to='parties.party')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemServesSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Основное'), ('backup', 'Резерв'), ('partial', 'Частичное')], default='primary', max_length=16)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_systems', to='building_passport.space')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_spaces', to='engineering_systems.buildingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='SystemServesZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Основное'), ('backup', 'Резерв'), ('partial', 'Частичное')], default='primary', max_length=16)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_zones', to='engineering_systems.buildingsystem')),
            ],
        ),
    ]
