# Generated by Django 6.0.7 on 2026-07-27 14:57

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineering_systems', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemserveszone',
            name='zone',
            field=models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='serving_systems', to='zones.zone'),
        ),
        migrations.AddIndex(
            model_name='buildingsystem',
            index=models.Index(fields=['catalog'], name='bs_catalog_idx'),
        ),
        migrations.AddConstraint(
            model_name='buildingsystem',
            constraint=models.CheckConstraint(condition=models.Q(('criticality__gte', 1), ('criticality__lte', 5)), name='bs_criticality_range'),
        ),
        migrations.AddConstraint(
            model_name='buildingsystem',
            constraint=models.UniqueConstraint(models.F('building_id'), django.db.models.functions.text.Lower('code'), condition=models.Q(('code__isnull', False)), name='bs_code_uq'),
        ),
    ]
