# Generated by Django 6.0.7 on 2026-07-28 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('design', 'Проектная документация'), ('as_built', 'Исполнительная документация'), ('scheme', 'Схема'), ('passport', 'Паспорт изделия'), ('manual', 'Руководство по эксплуатации'), ('certificate', 'Сертификат'), ('act', 'Акт'), ('protocol', 'Протокол испытаний / замеров'), ('permit', 'Разрешение'), ('expertise', 'Заключение экспертизы'), ('contract', 'Договор'), ('report', 'Отчёт'), ('photo', 'Фотофиксация'), ('other', 'Прочее')], max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('doc_no', models.CharField(blank=True, max_length=128, null=True)),
                ('file_uri', models.TextField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('revision', models.CharField(blank=True, max_length=32, null=True)),
                ('attrs', models.JSONField(blank=True, db_default={}, default=dict)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuer_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='parties.party')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='parties.org')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('pk', models.CompositePrimaryKey('document_id', 'entity_type', 'entity_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('space', 'Пространство'), ('zone', 'Зона'), ('building_element', 'Конструктив'), ('building_system', 'Система'), ('asset', 'Оборудование'), ('space_requirement', 'Требование'), ('element_survey', 'Обследование'), ('element_repair', 'Ремонт'), ('party', 'Контрагент')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='documents.document')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kind', '-issued_at'], name='document_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('valid_until__isnull', False)), fields=['valid_until'], name='document_expiry'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['entity_type', 'entity_id'], name='document_link_entity'),
        ),
    ]
