# Generated by Django 6.0.7 on 2026-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlink',
            name='pk',
        ),
        migrations.AddField(
            model_name='documentlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(fields=('document', 'entity_type', 'entity_id'), name='document_link_uq'),
        ),
    ]
