# Generated by Django 6.0.7 on 2026-07-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_dictdocumentrole'),
        ('documents', '0002_remove_documentlink_pk_documentlink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.dictdocumentrole'),
            preserve_default=False,
        ),
    ]
