# Generated by Django 6.0.7 on 2026-08-13 13:52

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentlink_role'),
        ('parties', '0005_orgmembership_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='page_count',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_uri',
            field=models.FileField(blank=True, max_length=512, upload_to=documents.models.document_file_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='parties.org'),
        ),
    ]
