# Generated by Django 6.0.7 on 2026-08-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_dictdocumentrole'),
        ('documents', '0004_alter_document_options_remove_document_page_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.dictdocumentrole'),
        ),
    ]
