# Generated by Django 6.0.7 on 2026-08-15 11:49

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentlink_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTwin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('markdown', models.FileField(max_length=512, upload_to=documents.models.twin_file_path, verbose_name='маркдаун')),
                ('unmatched_images', models.JSONField(default=list, editable=False, verbose_name='неразрешённые ссылки')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twin', to='documents.document', verbose_name='документ')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'близнец',
                'verbose_name_plural': 'близнецы',
            },
        ),
        migrations.CreateModel(
            name='TwinImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='имя')),
                ('file', models.FileField(max_length=512, upload_to=documents.models.twin_image_path, verbose_name='файл')),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.documenttwin', verbose_name='близнец')),
            ],
            options={
                'verbose_name': 'картинка близнеца',
                'verbose_name_plural': 'картинки близнеца',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('twin', 'name'), name='twin_image_uq')],
            },
        ),
    ]
