# Generated by Django 6.0.7 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenttwin_twinimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='entity_type',
            field=models.CharField(choices=[('space', 'Пространство'), ('zone', 'Зона'), ('building_element', 'Конструктив'), ('building_system', 'Система'), ('asset', 'Оборудование'), ('space_requirement', 'Требование'), ('element_survey', 'Обследование'), ('element_repair', 'Ремонт'), ('party', 'Контрагент'), ('lease', 'Аренда')], max_length=32),
        ),
    ]
