"""Условия договора, и строка для каждого договора, который уже лежит.

Таблица заводится пустой, а вслед за ней — по строке на каждый документ вида «Договор»,
сколько бы их ни лежало. Условия заводятся на договор сразу, заполненные или нет (ADR 0035):
полка договоров держится на том, что строка есть у каждого, и договор, у которого её нет,
пропал бы с неё молча — а заведена она ровно затем, чтобы ни одно обязательство не потерялось.

На день этой миграции договоров в настоящих данных ноль: `load_real_data` не заводит ни
одного, потому что заводить нечего. Строк она поэтому напишет столько же — и напишет их
всем, кто ляжет между этим днём и тем, когда реестр договоров УК станет исходным файлом.
"""

# Generated by Django 6.0.7 on 2026-09-16 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


#: Вид документа, у которого условия бывают. Написан строкой, а не взят с модели: миграция
#: читает схему того дня, когда её пишут, и `Document.Kind` завтрашнего дня о вчерашней
#: строке ничего не знает.
CONTRACT = "contract"


def give_every_contract_its_terms(apps, schema_editor):
    """По строке условий каждому уже лежащему договору — пустой, но существующей."""
    Document = apps.get_model("documents", "Document")
    ContractTerms = apps.get_model("documents", "ContractTerms")

    ContractTerms.objects.bulk_create(
        ContractTerms(document=document)
        for document in Document.objects.filter(kind=CONTRACT, terms__isnull=True)
    )


def take_the_terms_away(apps, schema_editor):
    """Откат уносит условия вместе с таблицей — отдельного шага здесь нет.

    Строки писались пустыми, но кто-то мог их заполнить, и второго места, где контрагент и
    срок договора записаны, в проекте нет. Откат этой миграции — это отказ от договоров
    целиком, и он говорит об этом тем, что удаляет таблицу, а не тем, что чистит её.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documentlink_entity_type'),
        ('parties', '0008_party_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, choices=[('lease', 'Аренда помещений'), ('extra_services', 'Доп услуги'), ('operation', 'Эксплуатация'), ('capital_works', 'Капитальные работы'), ('supply', 'Поставка ТМЦ')], max_length=16, null=True, verbose_name='вид договора')),
                ('is_perpetual', models.BooleanField(default=False, verbose_name='бессрочность')),
                ('auto_prolongs', models.BooleanField(default=False, verbose_name='автопролонгация')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='parties.party', verbose_name='контрагент')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='documents.document', verbose_name='документ')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'условия договора',
                'verbose_name_plural': 'условия договоров',
            },
        ),
        migrations.RunPython(give_every_contract_its_terms, take_the_terms_away),
    ]
