# Generated by Django 6.0.7 on 2026-07-27 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictSpaceSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('short_name', models.CharField(max_length=1024, unique=True)),
                ('sort_order', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('type', models.TextField(choices=[('project', 'Проект'), ('site', 'Площадка'), ('building', 'Здание'), ('wing', 'Блок / секция / крыло'), ('floor', 'Этаж'), ('mezzanine', 'Антресоль'), ('room', 'Помещение'), ('shaft', 'Шахта'), ('stairwell', 'Лестничная клетка'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('territory', 'Прилегающая территория'), ('parking_spot', 'Машиноместо'), ('void', 'Проём второго света / атриум'), ('other', 'Прочее')])),
                ('grp', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
