# Generated by Django 6.0.7 on 2026-09-10 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_dictdocumentrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('short_name', models.CharField(max_length=1024, unique=True)),
                ('sort_order', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'банки',
            },
        ),
        migrations.CreateModel(
            name='DictLineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('short_name', models.CharField(max_length=1024, unique=True)),
                ('sort_order', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сфера деятельности',
                'verbose_name_plural': 'сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='DictProfessionalHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('short_name', models.CharField(max_length=1024, unique=True)),
                ('sort_order', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь')], verbose_name='месяц')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='число')),
                ('week_of_month', models.SmallIntegerField(blank=True, choices=[(1, 'первая'), (2, 'вторая'), (3, 'третья'), (4, 'четвёртая'), (-1, 'последняя')], null=True, verbose_name='неделя месяца')),
                ('weekday', models.SmallIntegerField(blank=True, choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'суббота'), (7, 'воскресенье')], null=True, verbose_name='день недели')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line_of_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='dictionary.dictlineofbusiness', verbose_name='сфера деятельности')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профессиональный праздник',
                'verbose_name_plural': 'профессиональные праздники',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('day__isnull', False), ('week_of_month__isnull', True), ('weekday__isnull', True)), models.Q(('day__isnull', True), ('week_of_month__isnull', False), ('weekday__isnull', False)), _connector='OR'), name='professional_holiday_one_rule')],
            },
        ),
    ]
