# Generated by Django 6.0.7 on 2026-07-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('site', 'Площадка'), ('building', 'Здание'), ('wing', 'Блок / секция / крыло'), ('floor', 'Этаж'), ('mezzanine', 'Антресоль'), ('room', 'Помещение'), ('shaft', 'Шахта'), ('stairwell', 'Лестничная клетка'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('territory', 'Прилегающая территория'), ('parking_spot', 'Машиноместо'), ('void', 'Проём второго света / атриум'), ('other', 'Прочее')])),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_common', models.BooleanField(default=False)),
                ('is_leasable', models.BooleanField(default=False)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subspace', to='dictionary.dictbuilding')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subspace', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
