# Generated by Django 6.0.7 on 2026-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.TextField(choices=[('project', 'Проект'), ('site', 'Площадка'), ('building', 'Здание'), ('wing', 'Блок / секция / крыло'), ('floor', 'Этаж'), ('mezzanine', 'Антресоль'), ('room', 'Помещение'), ('shaft', 'Шахта'), ('stairwell', 'Лестничная клетка'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('territory', 'Прилегающая территория'), ('parking_spot', 'Машиноместо'), ('void', 'Проём второго света / атриум'), ('other', 'Прочее')]),
        ),
    ]
