# Generated by Django 6.0.7 on 2026-07-27 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0002_alter_space_type'),
        ('dictionary', '0002_dictspacesubtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictspacesubtype'),
        ),
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
