# Generated by Django 6.0.7 on 2026-07-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0003_space_subtype_alter_space_id'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='level_elevation_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='parties.org'),
        ),
        migrations.CreateModel(
            name='BuildingPassport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.OneToOneField(db_column='space_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passport', serialize=False, to='building_passport.space')),
                ('cadastral_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Кадастровый номер')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('year_commissioned', models.IntegerField(blank=True, null=True)),
                ('year_last_major_repair', models.IntegerField(blank=True, null=True)),
                ('building_class', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('industrial', 'Производственное'), ('other', 'Прочее')], max_length=16, null=True)),
                ('floors_above', models.IntegerField(blank=True, null=True)),
                ('floors_below', models.IntegerField(blank=True, null=True)),
                ('structural_scheme', models.CharField(blank=True, help_text='монолит | сборный каркас | панель | кирпич | металлокаркас', max_length=64, null=True)),
                ('fire_resistance_degree', models.CharField(blank=True, max_length=16, null=True, verbose_name='Степень огнестойкости')),
                ('functional_fire_class', models.CharField(blank=True, max_length=16, null=True, verbose_name='Класс функциональной пожарной опасности')),
                ('structural_fire_class', models.CharField(blank=True, max_length=16, null=True, verbose_name='Класс конструктивной пожарной опасности')),
                ('seismic_points', models.IntegerField(blank=True, null=True, verbose_name='Расчётная сейсмичность, баллы')),
                ('energy_class', models.CharField(blank=True, max_length=8, null=True)),
                ('design_occupancy', models.IntegerField(blank=True, null=True)),
                ('commissioning_act_no', models.CharField(blank=True, max_length=64, null=True)),
                ('attrs', models.JSONField(blank=True, db_default={}, default=dict)),
                ('builder_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='built_buildings', to='parties.party')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('designer_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designed_buildings', to='parties.party')),
                ('operator_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_buildings', to='parties.party')),
                ('owner_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_buildings', to='parties.party')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'паспорт здания',
                'verbose_name_plural': 'паспорта зданий',
                'db_table': 'building_passport',
            },
        ),
    ]
