# Generated by Django 6.0.7 on 2026-07-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0004_space_level_elevation_m_space_org_buildingpassport'),
        ('dictionary', '0003_dictrequirementcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_num', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('norm_ref', models.CharField(blank=True, help_text='Пункт норматива или ТЗ', max_length=255, null=True)),
                ('actual_num', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('actual_text', models.TextField(blank=True, null=True)),
                ('measured_at', models.DateField(blank=True, null=True)),
                ('is_compliant', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.dictrequirementcode')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'space_requirement',
                'indexes': [models.Index(condition=models.Q(('is_compliant', False)), fields=['space'], name='sr_noncompliant')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value_num__isnull', False), ('value_text__isnull', False), ('value_bool__isnull', False), _connector='OR'), name='sr_has_value'), models.UniqueConstraint(fields=('space', 'code'), name='space_requirement_uq')],
            },
        ),
    ]
