# Generated by Django 6.0.7 on 2026-07-27 13:26

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0005_spacerequirement'),
        ('dictionary', '0004_dictareakind_dictspacerelationkind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buildingpassport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='spacerequirement',
            table=None,
        ),
        migrations.CreateModel(
            name='SpaceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('measured_at', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('bti', 'Обмер БТИ'), ('as_built', 'Исполнительная'), ('design', 'Проект'), ('survey', 'Обмер на месте'), ('bim', 'Модель BIM'), ('lease_contract', 'Договор аренды'), ('estimate', 'Оценка')], max_length=32, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.dictareakind')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('value_m2__gte', 0)), name='space_area_positive'), models.UniqueConstraint(fields=('space', 'kind'), name='space_area_uq')],
            },
        ),
        migrations.CreateModel(
            name='SpaceCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_history', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('code'), name='space_code_hist_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpaceLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('space_id', 'related_id', 'relation_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='building_passport.space')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.dictspacerelationkind')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['related', 'relation'], name='space_link_rev')],
                'constraints': [models.CheckConstraint(condition=models.Q(('related_id', models.F('space_id')), _negated=True), name='space_link_no_self')],
            },
        ),
    ]
