# Generated by Django 6.0.7 on 2026-07-28 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0006_alter_buildingpassport_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings_space', to='building_passport.space'),
        ),
    ]
