# Generated by Django 6.0.7 on 2026-07-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0007_alter_space_building'),
        ('dictionary', '0005_dictassetrelationkind_dictconditiongrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='dictionary.dictspacestatus'),
        ),
        migrations.AddField(
            model_name='space',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings_spaces', to='building_passport.space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='dictionary.dictspacesubtype'),
        ),
    ]
