# Generated by Django 6.0.7 on 2026-07-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0008_space_status_space_valid_from_space_valid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
