# Generated by Django 6.0.7 on 2026-07-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0009_alter_space_area_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='is_common',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_leasable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
