# Generated by Django 6.0.7 on 2026-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0010_alter_space_is_common_alter_space_is_leasable'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpassport',
            name='apartments_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='balcony_loggia_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='building_footprint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='building_passport_naming',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='building_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='intended_purpose',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='non_residential_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='number_of_floors',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='passport_prepared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='physical_wear_tear',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='property_category',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='region',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='region_district',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='registry_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='series_project_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='settlement',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='settlement_district',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='signer_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='total_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingpassport',
            name='wall_material',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
