# Generated by Django 6.0.7 on 2026-08-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0011_buildingpassport_apartments_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpassport',
            name='building_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
