# Generated by Django 6.0.7 on 2026-08-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0013_downtown_org_and_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpassport',
            name='balcony_loggia_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpassport',
            name='building_footprint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpassport',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpassport',
            name='non_residential_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpassport',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
