# Generated by Django 6.0.7 on 2026-08-07 14:41

import building_passport.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0016_clear_remaining_placeholders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=building_passport.models.plan_file_path, verbose_name='файл SVG')),
                ('view_box', models.CharField(editable=False, max_length=128, verbose_name='viewBox')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='building_passport.space', verbose_name='этаж')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'поэтажный план',
                'verbose_name_plural': 'поэтажные планы',
                'ordering': ('-valid_from',),
            },
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_d', models.TextField(verbose_name='данные пути')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='building_passport.space', verbose_name='помещение')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='building_passport.floorplan', verbose_name='план')),
            ],
            options={
                'verbose_name': 'контур',
                'verbose_name_plural': 'контуры',
                'constraints': [models.UniqueConstraint(fields=('plan', 'space'), name='contour_uq')],
            },
        ),
    ]
