# Generated by Django 6.0.7 on 2026-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_passport', '0017_floorplan_contour'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='unmatched_ids',
            field=models.JSONField(default=list, editable=False, verbose_name='непривязанные пути'),
        ),
    ]
