# Generated by Django 6.0.7 on 2026-08-11 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_passport', '0018_floorplan_unmatched_ids'),
        ('parties', '0006_alter_partyrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='номер')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='дата подписания')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='parties.org', verbose_name='организация')),
                ('prolongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prolonged_by', to='leases.lease', verbose_name='пролонгирует договор')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='parties.party', verbose_name='арендатор')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'договор аренды',
                'verbose_name_plural': 'договоры аренды',
                'ordering': ('-valid_from',),
            },
        ),
        migrations.CreateModel(
            name='LeaseSubject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ставка')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='договорная площадь')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='leases.lease', verbose_name='договор')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_subjects', to='building_passport.space', verbose_name='помещение')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'предмет договора',
                'verbose_name_plural': 'предметы договора',
                'constraints': [models.UniqueConstraint(fields=('lease', 'space'), name='lease_subject_uq')],
            },
        ),
    ]
