# Generated by Django 6.0.7 on 2026-08-28 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_passport', '0018_floorplan_unmatched_ids'),
        ('parties', '0006_alter_partyrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='арендуемая площадь, м²')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ставка за м² в месяц')),
                ('contract_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='номер договора')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases_let', to='parties.party', verbose_name='арендодатель')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='building_passport.space', verbose_name='помещение')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='parties.party', verbose_name='арендатор')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'аренда',
                'verbose_name_plural': 'аренды',
                'ordering': ('-valid_from', '-created_at'),
            },
        ),
    ]
