# Generated by Django 6.0.7 on 2026-07-27 14:57

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_passport', '0006_alter_buildingpassport_table_and_more'),
        ('dictionary', '0005_dictassetrelationkind_dictconditiongrade_and_more'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='building_passport.space')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='dictionary.dictzonekind')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='parties.org')),
                ('parent', models.ForeignKey(blank=True, help_text='Отсек → секция → подзона', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='zones.zone')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetServesZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('asset_id', 'zone_id', 'role', blank=True, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField()),
                ('role', models.CharField(choices=[('primary', 'Основное'), ('backup', 'Резерв'), ('partial', 'Частичное')], default='primary', max_length=16)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_assets', to='zones.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('zone_id', 'space_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('coverage', models.DecimalField(decimal_places=4, default=1, help_text='Доля вхождения: помещение может лежать на границе двух отсеков', max_digits=5)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_links', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='zones.zone')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('from_asset_id', 'to_asset_id', 'relation_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('from_asset_id', models.UUIDField()),
                ('to_asset_id', models.UUIDField()),
                ('medium', models.CharField(blank=True, choices=[('electricity', 'Электроэнергия'), ('water', 'Вода'), ('sewage', 'Стоки'), ('heat', 'Тепло'), ('cold', 'Холод'), ('air', 'Воздух'), ('gas', 'Газ'), ('signal', 'Сигнал'), ('network', 'Сеть'), ('fuel', 'Топливо')], max_length=16, null=True)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.dictassetrelationkind')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['to_asset_id', 'relation'], name='asset_link_rev')],
                'constraints': [models.CheckConstraint(condition=models.Q(('to_asset_id', models.F('from_asset_id')), _negated=True), name='asset_link_no_self')],
            },
        ),
        migrations.CreateModel(
            name='AssetServesSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('asset_id', 'space_id', 'role', blank=True, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_column='asset_id')),
                ('role', models.CharField(choices=[('primary', 'Основное'), ('backup', 'Резерв'), ('partial', 'Частичное')], default='primary', max_length=16)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_assets', to='building_passport.space')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_serves_space',
                'indexes': [models.Index(fields=['space'], name='ass_space_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['primary', 'backup', 'partial'])), name='ass_role_check')],
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['building', 'kind'], name='zone_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.CheckConstraint(condition=models.Q(('parent_id', models.F('id')), _negated=True), name='zone_no_self'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(models.F('building_id'), models.F('kind'), django.db.models.functions.text.Lower('code'), condition=models.Q(('code__isnull', False), ('valid_to__isnull', True)), name='zone_code_uq'),
        ),
        migrations.AddIndex(
            model_name='assetserveszone',
            index=models.Index(fields=['zone'], name='asz_zone_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetserveszone',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['primary', 'backup', 'partial'])), name='asz_role_check'),
        ),
        migrations.AddIndex(
            model_name='zonespace',
            index=models.Index(fields=['space'], name='zone_space_rev'),
        ),
        migrations.AddConstraint(
            model_name='zonespace',
            constraint=models.CheckConstraint(condition=models.Q(('coverage__gt', 0), ('coverage__lte', 1)), name='zone_space_coverage'),
        ),
    ]
