"""
Django settings for bcmp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')


def _env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-$(lrakxf%&)x$a^3c-#yw81s!*kdwti9kjox6v0oy#keg==e0p',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'axes',

    'authentication',
    'assistant',
    'dictionary',
    'building_passport',
    'parties',
    'zones',
    'engineering_systems',
    'documents',
]

# django-extensions (runscript, shell_plus) is a dev dependency and is not
# installed into the runtime image, so importing it in production would stop the
# container from starting. It is loaded only where it exists and is used.
if DEBUG:
    INSTALLED_APPS.append('django_extensions')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be last: it turns the PermissionDenied raised by the axes backend into
    # the lockout response.
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'bcmp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # The AI manager panel sits in the shared layout, so its conversation
                # is needed on every screen.
                'assistant.context_processors.conversation',
            ],
        },
    },
]

WSGI_APPLICATION = 'bcmp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Brute-force protection (django-axes)
# Counts failed attempts by hooking authenticate(), so it covers both the login
# screen and /admin/ without either of them knowing about it.

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_RESET_ON_SUCCESS = True
# The nested list means AND: the lockout applies to the (address, login) pair, so
# someone guessing at a known login cannot lock its owner out of the system.
AXES_LOCKOUT_PARAMETERS = [['ip_address', 'username']]
AXES_LOCKOUT_TEMPLATE = 'auth/locked_out.html'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# The interface is entirely Russian-language — together with the admin and the error pages.
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Sources: hand-written assets plus the stylesheet the Node build stage compiles
# into static/css/ (ADR 0002).
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Destination of collectstatic — a separate directory, bind-mounted on the server
# and served by nginx. Must not overlap STATICFILES_DIRS.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Uploaded files (floor plans). A bind-mounted directory next to the SQLite
# database, so a redeploy does not discard them.
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', BASE_DIR / 'media')
# MEDIA_URL is deliberately left unset. Uploaded plans are served by a view that
# goes through the scoped-queryset chokepoint (ADR 0001); nginx has no /media/
# location, and without a MEDIA_URL `FieldFile.url` raises rather than quietly
# handing out a direct address to another client's floor plan.

LOGIN_REDIRECT_URL = "building_passport:bc_list"
LOGIN_URL = "/login/"

# Behind an SSL-terminating reverse proxy (nginx)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Every request reaches gunicorn from the Docker gateway, so REMOTE_ADDR is the
    # same address for all clients — locking one out would lock out everyone. nginx
    # must set `proxy_set_header X-Real-IP $remote_addr;`, which overwrites whatever
    # the client sent and is therefore the one address here that cannot be forged.
    # Only trusted when a proxy is actually in front, hence not in the DEBUG branch.
    AXES_IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_REAL_IP',)

    # nginx terminates TLS and redirects :80 to :443, so nothing is served over
    # plain HTTP any more: a session cookie has no reason to travel on one.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # A stolen session cookie skips password guessing altogether, so the browser
    # is told never to try HTTP for this host again. Note this is a year-long
    # promise across all of *.stata.kz — drop INCLUDE_SUBDOMAINS if any other
    # subdomain is still served over HTTP.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_SSL_REDIRECT is deliberately left off: nginx already redirects, and
    # SECURE_PROXY_SSL_HEADER means Django sees every proxied request as https.
